zeros:
    neck_joint: 2.617994
    l_shoulder_joint: 2.617994
    r_shoulder_joint: 2.617994
    l_biceps_joint: 2.617994
    r_biceps_joint: 2.617994
    l_elbow_joint: 2.617994
    r_elbow_joint: 2.617994
    l_hip_joint: 2.617994
    r_hip_joint: 2.617994
    l_thigh_joint: 2.617994
    r_thigh_joint: 2.617994
    l_knee_joint: 2.617994
    r_knee_joint: 2.617994
    l_ankle_joint: 2.617994
    r_ankle_joint: 2.617994
    l_foot_joint: 2.617994
    r_foot_joint: 2.617994

